name: software-example
title: Research software example
git_repo_url: https://github.com/petebachant/Software_Example
environments:
  main:
    kind: uv-venv
    path: requirements.txt
    python: "3.13.5"
    prefix: .venv
  nb:
    kind: uv-venv
    path: requirements-nb.txt
    python: "3.13.5"
    prefix: .venv2
pipeline:
  stages:
    run:
      kind: python-script
      script_path: run.py
      environment: main
      inputs:
        - model.py
      outputs:
        - two-dim/data
        - two-dim/snapshots
    post-process:
      kind: python-script
      script_path: postprocess.py
      environment: main
      inputs:
        - from_stage_outputs: run
        - model.py
        - analysis_utils.py
        - plotting_utils.py
        - plots.mplstyle
      outputs:
        - two-dim/analysis
    run-notebook:
      kind: jupyter-notebook
      notebook_path: example.ipynb
      environment: nb
      inputs:
        - model.py
      # outputs:
      #   - path: two-dim-nb
      #     delete_before_run: false
      html_storage: git
      cleaned_ipynb_storage: git
      executed_ipynb_storage: git
notebooks:
  - path: example.ipynb
    title: Example notebook
    stage: run-notebook
showcase:
  - notebook: example.ipynb
