name: software_example
title: Research example
description:
environments:
  main:
    path: requirements.txt
    kind: uv-venv
    prefix: .venv
    python: "3.13"
  nb:
    path: reqs-nb.txt
    kind: uv-venv
    prefix: .venv2
    python: '3.13'
pipeline:
  stages:
    run:
      kind: python-script
      script_path: run.py
      environment: main
      inputs:
        - model.py
      outputs:
        - two-dim/data
        - two-dim/snapshots
    post-process:
      kind: python-script
      script_path: postprocess.py
      environment: main
      inputs:
        - plotting_utils.py
        - analysis_utils.py
      outputs:
        - two-dim/analysis
    run-nb:
      kind: jupyter-notebook
      notebook_path: example.ipynb
      environment: nb
      inputs:
        - model.py
      html_storage: dvc
      executed_ipynb_storage: dvc
      cleaned_ipynb_storage: git
notebooks:
  - path: example.ipynb
    title: The notebook
    description:
    stage: run-nb
