name: software_example
title: Example
description:
environments:
  main:
    path: requirements.txt
    kind: uv-venv
    prefix: .venv
    python: "3.13"
pipeline:
  stages:
    run:
      kind: python-script
      script_path: run.py
      environment: main
      inputs:
        - model.py
      outputs:
        - two-dim/data
        - two-dim/snapshots
